Class AppExchange.Production Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="AppExchange.OpenAiTest" TestingEnabled="true" LogGeneralTraceEvents="true">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="AppPublish" Category="" ClassName="AppExchange.Operation" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}
